
from datetime import datetime
import pathlib
import matplotlib.pyplot as plt
import argparse


def plot(x_axis, y_axis, title):
    plt.xlabel("date")
    if "humidity" in str(title):
        plt.ylabel("Humidity (%)")
    else:
        plt.ylabel("Temperature (C)")
    plt.title(title)
    plt.plot(x_axis, y_axis)
    plt.gcf().autofmt_xdate()
    plt.show()


def main(args=None):
    dates = []
    readings = []
    with open(args.file, "r") as f:
        line = f.readline()
        while line:
            datetime_str = line.rpartition(":")[0].strip()
            value_str = float(line.rpartition(":")[2].strip())
            datetime_object = datetime.strptime(
                datetime_str, '%m/%d/%Y %H:%M:%S')
            dates.append(datetime_object)
            readings.append(value_str)
            line = f.readline()
    if len(dates) > 0 and len(readings) > 0:
        plot(dates, readings, args.file)
    else:
        print("cannot generate plot")


if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description=(
            f"Plotting diagram"
        )
    )
    parser.add_argument(
        "--file",
        "-f",
        type=pathlib.Path,
        required=True,
        help="input data file, generated by the sensor script",
    )
    args = parser.parse_args()

    main(args)
